# Generated by Django 3.2.4 on 2021-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
